name: Docs

on:
  push:
    branches: [ main ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Markdown Link Check
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-verbose-mode: 'yes'
          config-file: '.markdown-link-check.json'
          folder-path: '.,docs'

  hygiene:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ensure no build system files
        run: |
          set -e
          test ! -e build.gradle.kts || (echo "build.gradle.kts should not exist" && exit 1)
          test ! -e settings.gradle.kts || (echo "settings.gradle.kts should not exist" && exit 1)
          test ! -d gradle || (echo "gradle/ should not exist" && exit 1)
          test ! -d src || (echo "src/ should not exist" && exit 1)
          test ! -d packaging || (echo "packaging/ should not exist" && exit 1)
          test ! -d bin || (echo "bin/ should not exist" && exit 1)

  quick_validation:
    name: Quick Validation
    runs-on: ubuntu-latest
    needs: [links, hygiene]
    steps:
      - name: Quick validation passed
        run: echo "Links and hygiene checks completed"

  quality_checks:
    name: Quality Checks
    runs-on: ubuntu-latest
    needs: [hygiene]
    steps:
      - name: Quality checks passed
        run: echo "Hygiene checks completed"
