name: Java CLI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    name: Java CLI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - name: Install Gradle via SDKMAN
        run: |
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install gradle 8.7
          gradle -v
      - name: Build and Test (cli-java)
        run: |
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          gradle -p cli-java test --no-daemon --stacktrace